"""Stage A -- obtain the KTester test class that seeds the fusion.

Two providers:

``artifact``
    Install the released KTester test class shipped with the dataset.  No LLM
    call, so a fusion run costs exactly one model's worth of tokens (Stage B).
    This is the default and is what the current observation exercises.

``generate``
    Re-run KTester's own pipeline against an OpenAI-compatible endpoint.  The
    KTester checkout is copied into the run root and patched for Linux before
    use, so the paper's repository is never modified.  This reproduces the
    approach rather than reusing its outputs, which matters when the seed must
    come from the same model as Stage B.
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import config
from pipeline import mutgen_bridge as mb


# =========================================================================
# artifact provider
# =========================================================================
def released_test_sources(source_module: Path, task: dict) -> list[Path]:
    """The KTester-generated test class(es) for this focal method."""
    return mb.discover_reference_tests(source_module, task)


def install_seed(
    seed_sources: list[Path], source_module: Path, build_dir: Path
) -> list[Path]:
    """Copy the seed test class into the isolated workspace."""
    installed = []
    for source in seed_sources:
        destination = build_dir / source.relative_to(source_module)
        destination.parent.mkdir(parents=True, exist_ok=True)
        # copyfile, not copy2: Maven must see a newer mtime than the scaffold
        # it replaces, otherwise it skips recompilation of the same FQN.
        shutil.copyfile(source, destination)
        installed.append(destination)
    return installed


# =========================================================================
# generate provider -- reproduce the KTester pipeline
# =========================================================================
# KTester ships Windows-only assumptions.  These are applied to a private copy.
LINUX_PATCHES: list[tuple[str, str, str]] = [
    (
        "preparation.py",
        '"-Djava.class.path=./Java/project-info-process.jar;./Java/project-index-builder.jar"',
        '"-Djava.class.path=./Java/project-info-process.jar:./Java/project-index-builder.jar"',
    ),
    (
        "generate_unit_test.py",
        '"-Djava.class.path=./Java/project-info-process.jar;./Java/project-index-builder.jar"',
        '"-Djava.class.path=./Java/project-info-process.jar:./Java/project-index-builder.jar"',
    ),
    (
        "procedure/workspace_preparation.py",
        'libs ="target/classes;"+ \';\'.join(lib_list)',
        'libs ="target/classes:"+ \':\'.join(lib_list)',
    ),
    (
        "tools/execute_test.py",
        'test_dependencies = f"libs/*;target/test-classes;target/classes;{self.dependency_fd}/*"',
        'test_dependencies = f"libs/*:target/test-classes:target/classes:{self.dependency_fd}/*"',
    ),
    # `subprocess.run(['cd', d, '&&', 'javac', ...], shell=True)` executes only
    # `cd` on POSIX. Run the compiler directly in the project directory instead.
    (
        "tools/execute_test.py",
        "        script = self.cd_cmd + compile_cmd\n"
        '        self.logger.info(" ".join(compile_cmd))\n'
        "        result = subprocess.run(script, capture_output=True, text=True, shell=True, encoding=\"utf-8\")",
        "        self.logger.info(\" \".join(compile_cmd))\n"
        "        result = subprocess.run(compile_cmd, cwd=self.cd_cmd[1], capture_output=True, text=True, encoding=\"utf-8\")",
    ),
]

SETTINGS_TEMPLATE = '''"""Generated by observation_fuse -- do not edit by hand."""


class FileStructure:
    DEPENDENCY_PATH = {dependency_path!r}
    DATASET_PATH = {dataset_path!r}
    CODE_INFO_PATH = {code_info_path!r}
    BASELINE_PATH = {baseline_path!r}
    PROMPT_PATH = {prompt_path!r}
    FIX_PATH = {fix_path!r}
    RESPONSE_PATH = {response_path!r}
    TESTCLASSS_PATH = {testclass_path!r}
    REPORT_PATH = {report_path!r}


class LLMSettings:
    MODEL = {model!r}
    API_ACCOUNTS = [{{"base_url": {base_url!r}, "api_key": {api_key!r}}}]
    TEMPERATURE = {temperature!r}


class TaskSettings:
    PROJECTS = {projects!r}
    CASES_LIST = {cases!r}
    PROMPT_LIST = ["condition", "io", "exception"]
    CASE_THEN_CODE = True
    SAVE_INTER_RESULT = True
    COMPILE_TEST = True
    REPETITION_NUM = 1
    MAX_WORKERS = 1
    FIX_TRIES = {fix_tries!r}
    SIM_TOP_K = "10"


class BaseLine:
    BASELINES = []
    BASELINE_PATH = {baseline_path!r}
    UTGEN_DATA = ""
    CHATUNITEST_DATA = ""


class TimeRecord:
    TIME_RECORD_PATH = {time_record_path!r}
'''


@dataclass
class KTesterRuntime:
    """A patched, self-contained copy of KTester/code plus its knowledge index."""

    root: Path
    index_root: Path
    applied_patches: list[str]

    def activate(self) -> None:
        if str(self.root) not in sys.path:
            sys.path.insert(0, str(self.root))


def materialize_runtime(run_root: Path, force: bool = False) -> KTesterRuntime:
    """Copy KTester/code into the run root, apply the Linux fixes, wire the index."""
    runtime = run_root / "ktester_runtime"
    source = config.KTESTER_ROOT / "code"
    if not source.is_dir():
        raise SystemExit(f"Không tìm thấy KTester code: {source}")

    if force and runtime.exists():
        shutil.rmtree(runtime)
    applied: list[str] = []
    if not runtime.exists():
        shutil.copytree(
            source,
            runtime,
            ignore=shutil.ignore_patterns("__pycache__", "settings.py"),
        )
        for relative, old, new in LINUX_PATCHES:
            target = runtime / relative
            if not target.is_file():
                continue
            text = target.read_text(encoding="utf-8")
            if old not in text:
                # Already POSIX-clean, or upstream changed. Neither is an error,
                # but record it so a silent no-op is visible in the manifest.
                applied.append(f"SKIPPED {relative}: pattern not found")
                continue
            target.write_text(text.replace(old, new), encoding="utf-8")
            applied.append(f"patched {relative}")

    index_root = _assemble_index(run_root)
    return KTesterRuntime(root=runtime, index_root=index_root, applied_patches=applied)


def _assemble_index(run_root: Path) -> Path:
    """KTester expects json/, codegraph/ and lucene/ under one CODE_INFO_PATH."""
    index_root = run_root / "ktester_index"
    index_root.mkdir(parents=True, exist_ok=True)
    wanted = {
        "json": config.KTESTER_INDEX_JSON,
        "codegraph": config.KTESTER_INDEX_CODEGRAPH,
        "lucene": config.KTESTER_INDEX_LUCENE,
    }
    for name, source in wanted.items():
        link = index_root / name
        if link.is_symlink() or link.exists():
            continue
        if not source.is_dir():
            raise SystemExit(
                f"Thiếu index '{name}' cho Stage A generate: {source}\n"
                "Tải archive project_lucene của KTester hoặc chạy "
                "`python preparation.py -P` để dựng lại."
            )
        link.symlink_to(source.resolve())
    return index_root


def write_settings(
    runtime: KTesterRuntime,
    task_dir: Path,
    project_name: str,
    task_id: str,
    workspace: Path,
) -> Path:
    """Emit the settings.py that KTester's modules import at load time."""
    gen_root = task_dir / "ktester_stage"
    content = SETTINGS_TEMPLATE.format(
        dependency_path=str(runtime.root / "dependencies"),
        # KTester joins DATASET_PATH with each project-url, and reads
        # dataset_info.json from the same directory.
        dataset_path=str(config.PROJECTS_ROOT),
        code_info_path=str(runtime.index_root),
        baseline_path=str(gen_root / "baseline"),
        prompt_path=str(gen_root / "<project>/prompts"),
        fix_path=str(gen_root / "<project>/fix"),
        response_path=str(gen_root / "<project>/responses"),
        testclass_path=str(gen_root / "<project>/test_classes"),
        report_path=str(gen_root / "<project>/reports"),
        time_record_path=str(gen_root / "time"),
        model=config.KTESTER_LLM_MODEL,
        base_url=config.KTESTER_LLM_BASE_URL,
        api_key=config.KTESTER_LLM_API_KEY,
        temperature=config.KTESTER_LLM_TEMPERATURE,
        projects=[project_name],
        cases=[task_id],
        fix_tries=3,
    )
    settings_path = runtime.root / "settings.py"
    settings_path.write_text(content, encoding="utf-8")
    (gen_root).mkdir(parents=True, exist_ok=True)
    (gen_root / "settings_used.py").write_text(content, encoding="utf-8")
    return settings_path


def generate_seed(
    run_root: Path,
    task_dir: Path,
    project_name: str,
    task: dict,
    workspace: Path,
    build_dir: Path,
    maven: str,
    logs_dir: Path,
) -> list[Path]:
    """Run KTester's own generation pipeline for exactly one focal method.

    Returns the generated test source paths inside the workspace.
    """
    config.require_ktester_api_key()
    runtime = materialize_runtime(run_root)
    write_settings(runtime, task_dir, project_name, task["id"], workspace)

    # KTester's repair loop shells out to `javac -cp @dependencies.txt` and to
    # the JUnit console launcher, so the module needs a flat libs/ directory.
    mb.run_command(
        [maven, "-q", *mb.SKIP_FLAGS, "dependency:copy-dependencies",
         "-DoutputDirectory=libs"],
        build_dir,
        logs_dir / "a1_ktester_dependencies.log",
        "ktester-dependencies",
    )
    mb.run_command(
        [maven, "-q", *mb.SKIP_FLAGS, "-DskipTests", "compile"],
        build_dir,
        logs_dir / "a2_ktester_compile.log",
        "ktester-compile",
    )
    libs = sorted((build_dir / "libs").glob("*.jar"))
    classpath = ":".join(["target/classes"] + [f"libs/{jar.name}" for jar in libs])
    (build_dir / "dependencies.txt").write_text(classpath, encoding="utf-8")

    runtime.activate()
    import jpype  # imported here so `artifact` runs never need JPype installed

    jars = ":".join(
        str(runtime.root / "Java" / name)
        for name in ("project-info-process.jar", "project-index-builder.jar")
    )
    if not jpype.isJVMStarted():
        jpype.startJVM(jpype.getDefaultJVMPath(), "-Xmx4g", f"-Djava.class.path={jars}")

    dataset_info = mb.read_json(config.DATASET)
    # KTester resolves project paths as DATASET_PATH/<project-url>; point that
    # at the isolated workspace so generation never touches the shared dataset.
    scoped = {project_name: dict(dataset_info[project_name])}
    scoped[project_name]["project-url"] = str(build_dir)
    scoped[project_name]["focal-methods"] = [
        item for item in dataset_info[project_name]["focal-methods"]
        if item["id"] == task["id"]
    ]

    from settings import FileStructure as FS, TaskSettings as TS  # noqa: E402
    import procedure.generate_prompt as GenPrompt  # noqa: E402
    import procedure.generate_code as GenCode  # noqa: E402
    import procedure.post_process as Post  # noqa: E402

    _ensure_ktester_dirs(FS, project_name, task["id"])

    with mb.working_directory(runtime.root):
        GenPrompt.generate_init_prompts(FS, TS, scoped)
        GenPrompt.generate_test_case_prompts(FS, TS, scoped)
        GenCode.generate_testclass_framework(FS, TS, scoped)
        GenCode.generate_case_then_code(FS, TS, scoped)
        Post.verify_test_classes(FS, TS, scoped)

    produced = build_dir / task["test-path"]
    if not produced.is_file():
        raise RuntimeError(
            f"Stage A generate không tạo ra test class: {produced}. "
            f"Xem {task_dir / 'ktester_stage'}"
        )
    return [produced]


def _ensure_ktester_dirs(FS, project_name: str, task_id: str) -> None:
    for template in (FS.PROMPT_PATH, FS.FIX_PATH, FS.RESPONSE_PATH):
        Path(template.replace("<project>", project_name), task_id).mkdir(
            parents=True, exist_ok=True
        )
    for template in (FS.TESTCLASSS_PATH, FS.REPORT_PATH):
        Path(template.replace("<project>", project_name)).mkdir(
            parents=True, exist_ok=True
        )
    Path(FS.TESTCLASSS_PATH.replace("<project>", project_name), "temp").mkdir(
        parents=True, exist_ok=True
    )
